language: node_js
node_js:
  - "7"
  - "stable"
os:
  - linux
  - windows
matrix:
  fast_finish: true
install:
  - npm install
script:
  - npm test
  - snyk test
env:
  - CXX=g++-6
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
