language: node_js
node_js:
  - "stable"
  - "5.4"
os:
  - linux
  - osx
before_install:
  - echo "TRAVIS_OS_NAME is $TRAVIS_OS_NAME"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install nvm     ; fi
