language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
  - "stable"
os:
  - linux
matrix:
  fast_finish: true
install:
  - npm install
script:
  - npm test
env:
  - CXX=g++-6
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
